# Colors for better visibility
COLOR_RESET=\033[0m
COLOR_BLUE=\033[34m
COLOR_GREEN=\033[32m
COLOR_RED=\033[31m
COLOR_YELLOW=\033[33m

# Symbols
SYM_ARROW=➜
SYM_SUCCESS=✔
SYM_ERROR=✖
SYM_WARNING=⚠

# Image and Container Configuration
DOCKER_IMAGE := usabilitydynamics/udx-worker-php:latest
CONTAINER_NAME := udx-worker-php-container
VOLUMES ?= ./src/scripts:/var/www
ENV_FILE ?= .env
CMD ?= /bin/bash

# Platform and Build Configuration
MULTIPLATFORM := false
BUILD_PLATFORMS := linux/amd64,linux/arm64

# Port Configuration
HOST_PORT := 80
CONTAINER_PORT := 80

# PHP Configuration
PHP_VERSION := 8.4

# Paths
SRC_PATH := src
CONTAINER_SRC_PATH := /var/www

# Specific test script name
TEST_SCRIPT := 10_nginx_test.php

# Path for all test scripts
TESTS_PATH := $(CONTAINER_SRC_PATH)/tests

# Parallelism for running tests
TEST_PARALLELISM := 4

# Additional flags
FOLLOW_LOGS ?= false
