server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html index.htm;

    # Dynamic content funneled through index.php
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php${PHP_VERSION}.conf;
    }

    location ~ /\.ht {
        deny all;
    }
}
